import fs from 'fs/promises';
import path from 'path';
import {
  extractAndSaveKeywords,
  injectAutoGeneratedKeywordNames,
  removePathFromKeywords,
  replacePathInKeywords
} from './keywordService';
import { removePathFromSession, replacePathInSession } from './sessionService';
import {
  resolveWorkspacePath,
  type RenameWorkspacePathRequest,
  type WorkspacePathRequest
} from './workspacePath';

const fileTemplate = `<keyword name="" type="n">
### Variables and Conditions


### Claim

</keyword>

<details>
<summary>Proof</summary>

</details>`;

export interface WriteWorkspaceFileRequest extends WorkspacePathRequest {
  content: string;
}

export const readFile = async (request: WorkspacePathRequest): Promise<string> => {
  const filePath = resolveWorkspacePath(request);
  return fs.readFile(filePath, 'utf-8');
};

export const writeFile = async (request: WriteWorkspaceFileRequest): Promise<void> => {
  const { rootDir, content } = request;
  const filePath = resolveWorkspacePath(request);
  const nextContent = rootDir ? await injectAutoGeneratedKeywordNames(content, rootDir) : content;
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, nextContent, 'utf-8');
  if (rootDir) await extractAndSaveKeywords(filePath, nextContent, rootDir);
};

export const createFile = async (request: WorkspacePathRequest): Promise<void> => {
  const filePath = resolveWorkspacePath(request);
  const exists = await fs
    .access(filePath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, fileTemplate, 'utf-8');
};

export const createDirectory = async (request: WorkspacePathRequest): Promise<void> => {
  const dirPath = resolveWorkspacePath(request);
  const exists = await fs
    .access(dirPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(dirPath, { recursive: true });
};

export const deleteFile = async (request: WorkspacePathRequest): Promise<void> => {
  const { rootDir } = request;
  const filePath = resolveWorkspacePath(request);
  const stat = await fs.stat(filePath);
  if (stat.isDirectory()) throw new Error('path is directory');

  await fs.unlink(filePath);
  await removePathFromSession(rootDir, filePath);
  await removePathFromKeywords(rootDir, filePath);
};

export const renamePath = async (request: RenameWorkspacePathRequest): Promise<void> => {
  const { rootDir } = request;
  const oldPath = resolveWorkspacePath({ rootDir, path: request.oldPath });
  const newPath = resolveWorkspacePath({ rootDir, path: request.newPath });
  const exists = await fs
    .access(newPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(newPath), { recursive: true });
  await fs.rename(oldPath, newPath);
  await replacePathInSession(rootDir, oldPath, newPath);
  await replacePathInKeywords(rootDir, oldPath, newPath);
};
