import fs from 'fs/promises';
import path from 'path';
import {
  extractAndSaveKeywords,
  injectAutoGeneratedKeywordNames,
  removePathFromKeywords,
  replacePathInKeywords
} from './keywordService';
import { removePathFromSession, replacePathInSession } from './sessionService';

const fileTemplate = `<keyword name="" type="n">
### Variables and Conditions


### Claim

</keyword>

<details>
<summary>Proof</summary>

</details>`;

export const readFile = async (filePath: string): Promise<string> => {
  return fs.readFile(filePath, 'utf-8');
};

export const writeFile = async (
  filePath: string,
  content: string,
  rootDir: string
): Promise<void> => {
  const nextContent = rootDir ? await injectAutoGeneratedKeywordNames(content, rootDir) : content;
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, nextContent, 'utf-8');
  if (rootDir) await extractAndSaveKeywords(filePath, nextContent, rootDir);
};

export const createFile = async (filePath: string): Promise<void> => {
  const exists = await fs
    .access(filePath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, fileTemplate, 'utf-8');
};

export const createDirectory = async (dirPath: string): Promise<void> => {
  const exists = await fs
    .access(dirPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(dirPath, { recursive: true });
};

export const deleteFile = async (filePath: string, rootDir: string): Promise<void> => {
  const stat = await fs.stat(filePath);
  if (stat.isDirectory()) throw new Error('path is directory');

  await fs.unlink(filePath);
  await removePathFromSession(rootDir, filePath);
  await removePathFromKeywords(rootDir, filePath);
};

export const renamePath = async (
  oldPath: string,
  newPath: string,
  rootDir: string
): Promise<void> => {
  const exists = await fs
    .access(newPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(newPath), { recursive: true });
  await fs.rename(oldPath, newPath);
  await replacePathInSession(rootDir, oldPath, newPath);
  await replacePathInKeywords(rootDir, oldPath, newPath);
};
