import fs from 'fs/promises';
import path from 'path';
import {
  extractAndSaveKeywords,
  injectAutoGeneratedKeywordNames,
  removePathFromKeywords,
  replacePathInKeywords
} from './keywordService';
import { removePathFromSession, replacePathInSession } from './sessionService';
import {
  removeWorkspaceSearchPath,
  renameWorkspaceSearchPath,
  upsertWorkspaceSearchFile
} from './workspaceSearchIndexService';
import {
  resolveWorkspacePath,
  type RenameWorkspacePathRequest,
  type WorkspacePathRequest
} from './workspacePath';

const fileTemplate = `<keyword name="" type="n">
### Variables and Conditions


### Claim

</keyword>

<details>
<summary>Proof</summary>

</details>`;

export interface WriteWorkspaceFileRequest extends WorkspacePathRequest {
  content: string;
}

export interface SaveWorkspaceImageRequest {
  rootDir: string;
  preferredName?: string;
  mimeType: string;
  contentBase64: string;
}

export interface SaveWorkspaceImageResult {
  filename: string;
}

export interface ReadWorkspaceImageRequest {
  rootDir: string;
  filename: string;
}

export interface ReadWorkspaceImageResult {
  dataUrl: string;
}

const imageExtensionByMimeType: Record<string, string> = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/gif': '.gif',
  'image/webp': '.webp'
};

const imageMimeTypeByExtension: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp'
};

const imageDirectoryName = '_images';

const sanitizeFilenamePart = (value: string): string =>
  value
    .replace(/\.[^/.\\]+$/, '')
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);

const timestampFilenamePart = (): string =>
  new Date()
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 17);

const imageExtensionFor = (mimeType: string, preferredName?: string): string => {
  const preferredExtension = preferredName ? path.extname(preferredName).toLowerCase() : '';
  if (['.png', '.jpg', '.jpeg', '.gif', '.webp'].includes(preferredExtension)) {
    return preferredExtension === '.jpeg' ? '.jpg' : preferredExtension;
  }
  return imageExtensionByMimeType[mimeType] ?? '.png';
};

const nextAvailableImageFilename = async ({
  imageDir,
  preferredName,
  mimeType
}: {
  imageDir: string;
  preferredName?: string;
  mimeType: string;
}): Promise<string> => {
  const extension = imageExtensionFor(mimeType, preferredName);
  const sanitizedName = sanitizeFilenamePart(preferredName || 'image') || 'image';
  const baseName = `paste-${timestampFilenamePart()}-${sanitizedName}`;

  for (let index = 0; index < 1000; index += 1) {
    const suffix = index === 0 ? '' : `-${index + 1}`;
    const filename = `${baseName}${suffix}${extension}`;
    const exists = await fs
      .access(path.join(imageDir, filename))
      .then(() => true)
      .catch(() => false);
    if (!exists) return filename;
  }

  throw new Error('failed to allocate image filename');
};

export const readFile = async (request: WorkspacePathRequest): Promise<string> => {
  const filePath = resolveWorkspacePath(request);
  return fs.readFile(filePath, 'utf-8');
};

export const writeFile = async (request: WriteWorkspaceFileRequest): Promise<void> => {
  const { rootDir, content } = request;
  const filePath = resolveWorkspacePath(request);
  const nextContent = rootDir ? await injectAutoGeneratedKeywordNames(content, rootDir) : content;
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, nextContent, 'utf-8');
  if (rootDir) await extractAndSaveKeywords(filePath, nextContent, rootDir);
  if (rootDir) {
    await upsertWorkspaceSearchFile(rootDir, filePath).catch((error: unknown) => {
      console.error('Failed to update search index after write', error);
    });
  }
};

export const saveImage = async (
  request: SaveWorkspaceImageRequest
): Promise<SaveWorkspaceImageResult> => {
  if (!request.rootDir) throw new Error('rootDir is required');

  const imageDir = path.join(request.rootDir, imageDirectoryName);
  await fs.mkdir(imageDir, { recursive: true });
  const filename = await nextAvailableImageFilename({
    imageDir,
    preferredName: request.preferredName,
    mimeType: request.mimeType
  });
  await fs.writeFile(path.join(imageDir, filename), Buffer.from(request.contentBase64, 'base64'));
  return { filename };
};

export const readImage = async (
  request: ReadWorkspaceImageRequest
): Promise<ReadWorkspaceImageResult> => {
  if (!request.rootDir) throw new Error('rootDir is required');

  const imagePath = path.join(request.rootDir, imageDirectoryName, request.filename);
  const image = await fs.readFile(imagePath);
  const mimeType =
    imageMimeTypeByExtension[path.extname(request.filename).toLowerCase()] ?? 'image/png';
  return {
    dataUrl: `data:${mimeType};base64,${image.toString('base64')}`
  };
};

export const createFile = async (request: WorkspacePathRequest): Promise<void> => {
  const filePath = resolveWorkspacePath(request);
  const exists = await fs
    .access(filePath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, fileTemplate, 'utf-8');
  if (request.rootDir) {
    await upsertWorkspaceSearchFile(request.rootDir, filePath).catch((error: unknown) => {
      console.error('Failed to update search index after create', error);
    });
  }
};

export const createDirectory = async (request: WorkspacePathRequest): Promise<void> => {
  const dirPath = resolveWorkspacePath(request);
  const exists = await fs
    .access(dirPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(dirPath, { recursive: true });
};

export const deleteFile = async (request: WorkspacePathRequest): Promise<void> => {
  const { rootDir } = request;
  const filePath = resolveWorkspacePath(request);
  const stat = await fs.stat(filePath);
  if (stat.isDirectory()) throw new Error('path is directory');

  await fs.unlink(filePath);
  await removePathFromSession(rootDir, filePath);
  await removePathFromKeywords(rootDir, filePath);
  await removeWorkspaceSearchPath(rootDir, filePath).catch((error: unknown) => {
    console.error('Failed to update search index after delete', error);
  });
};

export const renamePath = async (request: RenameWorkspacePathRequest): Promise<void> => {
  const { rootDir } = request;
  const oldPath = resolveWorkspacePath({ rootDir, path: request.oldPath });
  const newPath = resolveWorkspacePath({ rootDir, path: request.newPath });
  const exists = await fs
    .access(newPath)
    .then(() => true)
    .catch(() => false);
  if (exists) throw new Error('already exists');

  await fs.mkdir(path.dirname(newPath), { recursive: true });
  await fs.rename(oldPath, newPath);
  await replacePathInSession(rootDir, oldPath, newPath);
  await replacePathInKeywords(rootDir, oldPath, newPath);
  await renameWorkspaceSearchPath({ rootDir, oldPath, newPath }).catch((error: unknown) => {
    console.error('Failed to update search index after rename', error);
  });
};
