// Code generated by MockGen. DO NOT EDIT.
// Source: paper.go
//
// Generated by this command:
//
//	mockgen --source=paper.go --destination=mock/mock_paper.go --package=mock_paper
//

// Package mock_paper is a generated GoMock package.
package mock_paper

import (
	context "context"
	reflect "reflect"

	paper "github.com/kavos113/tnet/services/papers-server/internal/logic/paper"
	model "github.com/kavos113/tnet/services/papers-server/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// OpenPaperRepository mocks base method.
func (m *MockStore) OpenPaperRepository(arg0 context.Context, arg1 model.LibraryRoot) (paper.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenPaperRepository", arg0, arg1)
	ret0, _ := ret[0].(paper.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenPaperRepository indicates an expected call of OpenPaperRepository.
func (mr *MockStoreMockRecorder) OpenPaperRepository(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenPaperRepository", reflect.TypeOf((*MockStore)(nil).OpenPaperRepository), arg0, arg1)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AttachTag mocks base method.
func (m *MockRepository) AttachTag(arg0 context.Context, arg1, arg2 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttachTag indicates an expected call of AttachTag.
func (mr *MockRepositoryMockRecorder) AttachTag(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTag", reflect.TypeOf((*MockRepository)(nil).AttachTag), arg0, arg1, arg2)
}

// CreatePaper mocks base method.
func (m *MockRepository) CreatePaper(arg0 context.Context, arg1 paper.CreatePaperInput) (model.Paper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaper", arg0, arg1)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaper indicates an expected call of CreatePaper.
func (mr *MockRepositoryMockRecorder) CreatePaper(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaper", reflect.TypeOf((*MockRepository)(nil).CreatePaper), arg0, arg1)
}

// DetachTag mocks base method.
func (m *MockRepository) DetachTag(arg0 context.Context, arg1, arg2 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DetachTag indicates an expected call of DetachTag.
func (mr *MockRepositoryMockRecorder) DetachTag(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachTag", reflect.TypeOf((*MockRepository)(nil).DetachTag), arg0, arg1, arg2)
}

// GetPaper mocks base method.
func (m *MockRepository) GetPaper(arg0 context.Context, arg1 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaper", arg0, arg1)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaper indicates an expected call of GetPaper.
func (mr *MockRepositoryMockRecorder) GetPaper(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaper", reflect.TypeOf((*MockRepository)(nil).GetPaper), arg0, arg1)
}

// GetPaperByIdentifiers mocks base method.
func (m *MockRepository) GetPaperByIdentifiers(arg0 context.Context, arg1, arg2 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaperByIdentifiers", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaperByIdentifiers indicates an expected call of GetPaperByIdentifiers.
func (mr *MockRepositoryMockRecorder) GetPaperByIdentifiers(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaperByIdentifiers", reflect.TypeOf((*MockRepository)(nil).GetPaperByIdentifiers), arg0, arg1, arg2)
}

// GetPaperByPDFPath mocks base method.
func (m *MockRepository) GetPaperByPDFPath(arg0 context.Context, arg1 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaperByPDFPath", arg0, arg1)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaperByPDFPath indicates an expected call of GetPaperByPDFPath.
func (mr *MockRepositoryMockRecorder) GetPaperByPDFPath(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaperByPDFPath", reflect.TypeOf((*MockRepository)(nil).GetPaperByPDFPath), arg0, arg1)
}

// ListPapers mocks base method.
func (m *MockRepository) ListPapers(arg0 context.Context, arg1 paper.ListFilter) ([]model.Paper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPapers", arg0, arg1)
	ret0, _ := ret[0].([]model.Paper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPapers indicates an expected call of ListPapers.
func (mr *MockRepositoryMockRecorder) ListPapers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPapers", reflect.TypeOf((*MockRepository)(nil).ListPapers), arg0, arg1)
}

// ListTags mocks base method.
func (m *MockRepository) ListTags(arg0 context.Context) ([]model.PaperTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", arg0)
	ret0, _ := ret[0].([]model.PaperTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockRepositoryMockRecorder) ListTags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockRepository)(nil).ListTags), arg0)
}

// SaveNote mocks base method.
func (m *MockRepository) SaveNote(arg0 context.Context, arg1, arg2 string) (model.Paper, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNote", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Paper)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SaveNote indicates an expected call of SaveNote.
func (mr *MockRepositoryMockRecorder) SaveNote(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNote", reflect.TypeOf((*MockRepository)(nil).SaveNote), arg0, arg1, arg2)
}

// UpsertTag mocks base method.
func (m *MockRepository) UpsertTag(arg0 context.Context, arg1, arg2 string) (model.PaperTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.PaperTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTag indicates an expected call of UpsertTag.
func (mr *MockRepositoryMockRecorder) UpsertTag(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTag", reflect.TypeOf((*MockRepository)(nil).UpsertTag), arg0, arg1, arg2)
}
