import fs from 'fs/promises';
import {
  extractKeywordContent,
  injectKeywordNames,
  parseKeywords
} from '@tnet/app-markdown/shared/keyword/keywordParser';
import { readJsonFileOrDefault, writeJsonFile } from '@tnet/main-core/storage/jsonFile';
import { keywordsFilePath, latestFilePath } from '@tnet/main-core/storage/paths';
import {
  resolveWorkspacePath,
  type WorkspacePathRequest
} from '@tnet/main-core/workspace/workspacePath';

export const loadKeywordIndex = async (rootDir: string): Promise<Record<string, string>> => {
  if (!rootDir) return {};
  return readJsonFileOrDefault<Record<string, string>>(keywordsFilePath(rootDir), {});
};

export interface KeywordContentRequest extends WorkspacePathRequest {
  name: string;
}

export const getKeywordContent = async ({
  name,
  ...pathRequest
}: KeywordContentRequest): Promise<string | null> => {
  if (!pathRequest.path || !name) return null;
  const filePath = resolveWorkspacePath(pathRequest);
  const content = await fs.readFile(filePath, 'utf-8');
  return extractKeywordContent(content, name);
};

export const injectAutoGeneratedKeywordNames = async (
  content: string,
  rootDir: string
): Promise<string> => {
  const latest = await readJsonFileOrDefault<Record<string, number>>(latestFilePath(rootDir), {});

  const nextContent = injectKeywordNames(content, (numberClass, prefix) => {
    const next = (latest[numberClass] ?? 0) + 1;
    latest[numberClass] = next;
    return `${prefix} ${numberClass}.${next}`;
  });

  await writeJsonFile(latestFilePath(rootDir), latest);
  return nextContent;
};

export const extractAndSaveKeywords = async (
  filePath: string,
  content: string,
  rootDir: string
): Promise<void> => {
  if (!rootDir) return;

  const keywords = await loadKeywordIndex(rootDir);
  for (const [key, value] of Object.entries(keywords)) {
    if (value === filePath) delete keywords[key];
  }

  for (const keyword of parseKeywords(content)) {
    if (keyword.noindex || !keyword.name) continue;
    keywords[keyword.name] = filePath;
  }

  await writeJsonFile(keywordsFilePath(rootDir), keywords);
};

export const removePathFromKeywords = async (
  rootDir: string,
  targetPath: string
): Promise<void> => {
  if (!rootDir) return;
  const keywords = await loadKeywordIndex(rootDir);
  for (const [key, value] of Object.entries(keywords)) {
    if (value === targetPath) delete keywords[key];
  }
  await writeJsonFile(keywordsFilePath(rootDir), keywords);
};

export const replacePathInKeywords = async (
  rootDir: string,
  oldPath: string,
  newPath: string
): Promise<void> => {
  if (!rootDir) return;
  const keywords = await loadKeywordIndex(rootDir);
  for (const [key, value] of Object.entries(keywords)) {
    if (value === oldPath) keywords[key] = newPath;
  }
  await writeJsonFile(keywordsFilePath(rootDir), keywords);
};
