import type * as grpc from '@grpc/grpc-js';
import { describe, expect, it, vi } from 'vitest';
import { PapersServerClient, type PapersServerGrpcClients } from './papersServerClient';

const createTestClient = (): PapersServerClient => {
  const clients = createGrpcClientStubs({
    libraryClient: {
      loadGlobalConfig: unaryStub((request: { userDataDir: string }) => ({
        libraryRoots: ['C:/papers'],
        activeLibraryRoot: request.userDataDir === 'C:/user-data' ? 'C:/papers' : '',
        lastOpenedDirectory: ''
      }))
    },
    paperClient: {
      getPaper: unaryStub(() => ({
        paper: {
          id: 'paper-1',
          title: 'Title',
          authors: ['A'],
          publishedYear: 0,
          venue: '',
          tags: ['tag'],
          hasPdf: true,
          abstract: '',
          doi: '',
          arxivId: '',
          url: '',
          pdfPath: 'papers/a.pdf',
          directoryPath: 'papers',
          noteContent: 'note'
        }
      }))
    },
    pdfClient: {
      loadPdfBytes: unaryStub(() => ({ bytes: new Uint8Array([1, 2, 3]) }))
    },
    tagClient: {
      listTags: unaryStub(() => ({ tags: [] }))
    }
  });
  return new PapersServerClient({ clients, userDataDir: 'C:/user-data' });
};

describe('PapersServerClient', () => {
  it('calls generated global config API with user data dir', async () => {
    const client = createTestClient();

    await expect(client.loadGlobalConfig()).resolves.toEqual({
      libraryRoots: ['C:/papers'],
      activeLibraryRoot: 'C:/papers',
      lastOpenedDirectory: undefined
    });
  });

  it('maps generated paper detail defaults to renderer types', async () => {
    const client = createTestClient();

    await expect(
      client.getPaper({ libraryRoot: 'C:/papers', paperId: 'paper-1' })
    ).resolves.toEqual({
      id: 'paper-1',
      title: 'Title',
      authors: ['A'],
      publishedYear: undefined,
      venue: undefined,
      tags: ['tag'],
      hasPdf: true,
      abstract: undefined,
      doi: undefined,
      arxivId: undefined,
      url: undefined,
      pdfPath: 'papers/a.pdf',
      directoryPath: 'papers',
      noteContent: 'note'
    });
  });

  it('returns generated bytes as an ArrayBuffer', async () => {
    const client = createTestClient();

    const bytes = await client.loadPdfBytes({ libraryRoot: 'C:/papers', pdfPath: 'papers/a.pdf' });

    expect([...new Uint8Array(bytes)]).toEqual([1, 2, 3]);
  });

  it('treats empty library requests as an unselected library state', async () => {
    const listPapers = vi.fn(() => {
      throw new Error('should not be called');
    });
    const listTags = vi.fn(() => {
      throw new Error('should not be called');
    });
    const clients = createGrpcClientStubs({
      paperClient: { listPapers: unaryStub(listPapers) },
      tagClient: { listTags: unaryStub(listTags) }
    });
    const client = new PapersServerClient({ clients, userDataDir: 'C:/user-data' });

    await expect(client.listPapers({ libraryRoot: '' })).resolves.toEqual([]);
    await expect(client.listTags({ libraryRoot: '' })).resolves.toEqual([]);
    await expect(client.getPaper({ libraryRoot: '', paperId: 'paper-1' })).resolves.toBeNull();
  });

  it('surfaces generated client errors', async () => {
    const clients = createGrpcClientStubs({
      paperClient: {
        listPapers: unaryErrorStub('invalid request')
      }
    });
    const client = new PapersServerClient({ clients, userDataDir: 'C:/user-data' });

    await expect(client.listPapers({ libraryRoot: 'C:/papers' })).rejects.toThrow(
      'invalid request'
    );
  });
});

const createGrpcClientStubs = (
  clients: Partial<Record<keyof PapersServerGrpcClients, Record<string, unknown>>>
): PapersServerGrpcClients => clients as unknown as PapersServerGrpcClients;

const unaryStub =
  <Input, Output>(handler: (input: Input) => Output) =>
  (input: Input, callback: (err: grpc.ServiceError | null, value?: Output) => void) => {
    callback(null, handler(input));
    return {} as grpc.ClientUnaryCall;
  };

const unaryErrorStub =
  (message: string) => (_input: unknown, callback: (err: grpc.ServiceError | null) => void) => {
    callback({ message } as grpc.ServiceError);
    return {} as grpc.ClientUnaryCall;
  };
